# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: "ubuntu:22"

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip
    - venv/

pylint:
  needs: []
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install .
    - pip install pylint pylint-exit anybadge pylint-gitlab PyQt5-stubs
  script:
    - mkdir ./pylint
    - pylint --output-format=text CTI Engine | tee ./pylint/pylint.log || pylint-exit $?
    - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
    - anybadge --label=Pylint --file=pylint/pylint.svg --value=$PYLINT_SCORE 2=red 4=orange 8=yellow 10=green
    - echo "Pylint score is $PYLINT_SCORE"
    - pylint --exit-zero --output-format=pylint_gitlab.GitlabCodeClimateReporter CTI Engine > codeclimate.json
  artifacts:
    paths:
      - public
      - ./pylint/
    reports:
      codequality: codeclimate.json
    when: always


mypy:
  needs: []
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install .
    - pip install PyQt5-stubs mypy
  script:
    - mypy CTI Engine --strict



